version: "2"
plugins:
  git-legal:
    enabled: true
    config:
      allow_affero_copyleft: true
      allow_strong_copyleft: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  markdownlint:
    enabled: true
    issue_override:
      severity: minor
  fixme:
    enabled: true
  eslint:
    enabled: true
exclude_patterns:
- "**/.idea/**/*"
- "**/.github/**/*"
- "**/build/**/*"
- "**/public/**/*"
- "**/node_modules/"
- "**/yarn.lock"
