sudo: false
os:
  - osx
  - linux
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
cache: yarn
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - node_js: "4"
    - node_js: "5"
    - node_js: "7"
before_install:
  - node --version
  - npm --version
install:
  - npm install -g gulp-cli yarn
  - yarn
script:
  - gulp validate
