language: node_js
node_js:
  - "10.14.2"
sudo: false
cache: yarn
before_install:
  - npm install -g yarn
  - "export CHROME_BIN=chromium-browser"
addons:
  chrome: stable # have Travis install chrome stable.
