'use strict';

const footerConfig = require('../../41-organisms/footer/footer.config').context;

module.exports = {
  preview: '@preview-overview-without-padding',
  context: {
    articles: [
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'Event title comes here',
        event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        label_text: 'Event'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'Event title comes here',
        event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag'],
        label_text: 'Event'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'News article title text',
        published_date: 'Gepost op Zaterdag 7 januari 2019',
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'Event title comes here',
        event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag'],
        label_text: 'Event'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'News article title text',
        published_date: 'Gepost op Zaterdag 7 januari 2019',
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'News article title text',
        published_date: 'Gepost op Zaterdag 7 januari 2019',
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag']
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'Event title comes here',
        event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        label_text: 'Event'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'Event title comes here',
        event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag'],
        label_text: 'Event'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'News article title text',
        published_date: 'Gepost op Zaterdag 7 januari 2019',
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'News article title text',
        published_date: 'Gepost op Zaterdag 7 januari 2019',
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag']
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'Event title comes here',
        event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag'],
        label_text: 'Event'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'Event title comes here',
        event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag'],
        label_text: 'Event'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'Event title comes here',
        event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag'],
        label_text: 'Event'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi?',
        title: 'Event title comes here',
        event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag'],
        label_text: 'Event'
      },
      {
        teaser_uid: 'uid',
        paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        title: 'News article title text',
        published_date: 'Gepost op Zaterdag 7 januari 2019',
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        link_text: 'Read more',
        link: '#',
        image_src: 'https://loremflickr.com/800/500/ghent',
        image_alt_text: 'alt text',
        image_ratio: '8:5',
        tags: ['Just some tag']
      }
    ],
    footerConfig
  }
};
