'use strict';

module.exports = {
  title: 'News page',
  status: 'alpha',
  preview: '@preview-overview-without-padding',
  context: {
    articles: [
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      },
      {
        teaser_uid: 'uid',
        teaser_paragraph_text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam corporis cumque debitis eligendi harum iste laborum quibusdam ut, vitae voluptate?',
        teaser_title: 'News article title text',
        teaser_event_date: true,
        text_1: 'From the 7th',
        datetime_1: '2019-01-07',
        text_2: 'until the 13th of January 2019',
        datetime_2: '2019-01-13',
        teaser_datetime: '2019-01-07',
        teaser_link_text: 'read more',
        teaser_link_link: '#',
        teaser_image_src: '/styleguide/img/stock/teaser_2.jpg',
        teaser_image_alt_text: 'alt text',
        teaser_tag: 'Just some tag'
      }
    ]
  }
};
