name: E-Mail Release Notification
on:
  release:
    types: [published]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify about a new release
      uses: ba-st-actions/email-release-notification@v3.0.0
      env:
        SENDGRID_API_TOKEN: ${{ secrets.SENDGRID_API_TOKEN }}
        RECIPIENTS_URL: ${{ secrets.RECIPIENTS_URL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        DISTRIBUTION_LISTS: ${{ secrets.DISTRIBUTION_LISTS }}
